dataset_params:
  multiply_input_layer: 1
  name: yin_yang
default_neuron_params:
  g_leak: 1.0
  leak: 0.0
  max_dw_norm: 0.2
  tau_mem: 1.0
  tau_syn: 1.0
  threshold: 2.6
network_layout:
  layers:
  - factor: 5
    name: Multiplex
  - name: BroadcastLayer
  - max_num_missing_spikes: 0.05
    monitor: true
    name: NeuronLayer
    neuron_params:
      jitter: 0.0
      threshold_noise_b2b_std: 0.04
      threshold_noise_fp_mean: 0.13
      threshold_noise_fp_std: 0.08
    size: 30
    trainable: true
    weights_mean: 1.0
    weights_std: 0.12
  - name: BroadcastLayer
  - max_num_missing_spikes: 0.05
    monitor: true
    name: NeuronLayer
    neuron_params:
      jitter: 0.0
      threshold_noise_b2b_std: 0.04
      threshold_noise_fp_mean: 0.13
      threshold_noise_fp_std: 0.08
    size: 3
    trainable: true
    weights_mean: 0.075
    weights_std: 0.15
  n_inputs: 4
training_params:
  batch_size: 40
  batch_size_eval: 200
  clip_weights_max: 2.1
  enforce_cpu: false
  epoch_number: 300
  epoch_snapshots:
  - 20
  - 50
  - 100
  - 200
  learning_rate: 0.002
  loss:
    delta_t: 0.3
    type: shift_invariant_MSE
  lr_scheduler:
    gamma: 0.95
    step_size: 20
    type: StepLR
  momentum: 0
  numpy_seed: 12345
  optimizer: adam
  print_step_percent: 5.0
  rounding_precision: 0.03333333333333333
  substrate: sim
  torch_seed: 2000
  training_noise: false
  use_forward_integrator: false
  weight_bumping_exp: true
  weight_bumping_targeted: true
  weight_bumping_value: 0.0005
