DEFAULT:
        calibration: calibrations/HWLICENCE.npz
        neuron_params:
                leak: 0.00
                threshold: 2.6
                g_leak: 1.
                tau_syn: 1.
                tau_mem: 1.
        scale_weights: 30
        synapse_bias: 1000
        taum : 6.
