dataset: 16x16_mnist
neuron_params:
  g_leak: 1.0
  leak: 0.0
  tau_syn: 1.0
  threshold: 1.0
network_layout:
  bias_times: []
  layer_sizes: [246, 10]
  n_biases: [0, 0]
  n_inputs: 256
  n_layers: 2
  weight_means: [0.01, 0.006]
  weight_stdevs: [0.03, 0.10]
training_params:
  alpha: 0.005
  batch_size: 200
  batch_size_eval: 1000
  beta: 1.
  enforce_cpu: false
  epoch_number: 200
  epoch_snapshots: [1, 30, 50, 100, 150]
  learning_rate: 0.003
  lr_scheduler: {gamma: 0.9, step_size: 10, type: StepLR}
  max_dw_norm: 0.2
  max_num_missing_spikes: [0.5, 0.5]
  momentum: 0
  numpy_seed: 12345
  optimizer: adam
  print_step_percent: 5.0
  resolution: 0.01
  sim_time: 3.0
  torch_seed: 420420
  training_noise: {mean: 0.0, std_dev: 0.3}
  use_forward_integrator: false
  use_hicannx: true
  weight_bumping_exp: true
  weight_bumping_targeted: true
  weight_bumping_value: 0.005
  xi: 0.2
