dataset: bars
neuron_params:
  g_leak: 1.0
  leak: 0.0
  tau_syn: 1.0
  threshold: 1.0
network_layout:
  bias_times: []
  layer_sizes: [10, 3]
  n_biases: [0, 0]
  n_inputs: 9
  n_layers: 2
  weight_means: [1.5, 1.0]
  weight_stdevs: [1.0, 0.6]
training_params:
  alpha: 0.003
  batch_size: 30
  batch_size_eval: 200
  beta: 1.
  enforce_cpu: False
  epoch_number: 500
  epoch_snapshots: [10, 35]
  learning_rate: 0.05
  lr_scheduler: {gamma: 1.0, step_size: 20, type: StepLR}
  max_dw_norm: 0.2
  max_num_missing_spikes: [0.5, 0.30]
  momentum: 0
  numpy_seed: 91231231
  optimizer: adam
  print_step_percent: 5.0
  resolution: 0.01
  sim_time: 4.0
  torch_seed: 91231231
  training_noise: false
  use_forward_integrator: false
  use_hicannx: true
  weight_bumping_exp: true
  weight_bumping_targeted: true
  weight_bumping_value: 0.005
  xi: 0.2
