dataset: yin_yang
neuron_params:
  g_leak: 1.0
  leak: 0.0
  tau_syn: 1.0
  threshold: 1.0
network_layout:
  bias_times: [[0.9, ], []]
  layer_sizes: [120, 3]
  n_biases: [1, 0]
  n_inputs: 4
  n_layers: 2
  weight_means: [0.100, 0.075]
  weight_stdevs: [0.12, 0.15]
training_params:
  batch_size: 200
  batch_size_eval: 200
  enforce_cpu: False
  epoch_number: 500
  epoch_snapshots: [1, 5, 10, 15, 50, 100, 150, 200, 300, 400]
  learning_rate: 0.04
  loss:
    type: MSE
    t_correct: 1.9
    t_wrong: 1.6
  lr_scheduler: {gamma: 0.95, step_size: 20, type: StepLR}
  max_dw_norm: 0.2
  max_num_missing_spikes: [0.3, 0.05]
  momentum: 0
  numpy_seed: 12345
  optimizer: adam
  print_step_percent: 5.0
  resolution: 0.01
  sim_time: 4.0
  torch_seed: 2000
  training_noise: false
  use_forward_integrator: false
  use_hicannx: true
  weight_bumping_exp: true
  weight_bumping_targeted: true
  weight_bumping_value: 0.0005
