dataset_params:
  name : yin_yang
default_neuron_params:
  g_leak: 1.0
  leak: 0.0
  tau_syn: 1.0
  tau_mem: 1.0
  threshold: 1.0
  max_dw_norm: 0.2
network_layout:
  layers:
    - name: Biases
      times: [0.9, ]
    - name: BroadcastLayer
    - name: NeuronLayer
      size: 50
      weights_mean: 0.1
      weights_std: 0.12
      max_num_missing_spikes: 0.3
      trainable: true
      monitor: true
    - name: BroadcastLayer
    - name: NeuronLayer
      size: 3
      weights_mean: 0.075
      weights_std: 0.15
      max_num_missing_spikes: 0.05
      trainable: true
      monitor: true
  n_inputs: 4
training_params:
  batch_size: 200
  batch_size_eval: 200
  enforce_cpu: False
  epoch_number: 400
  epoch_snapshots: [1, 5, 10, 15, 50, 100, 150, 200, 300]
  learning_rate: 0.04
  loss:
    type: MSE
    t_correct: 1.9
    t_wrong: 1.6
  lr_scheduler: {gamma: 0.95, step_size: 20, type: StepLR}
  momentum: 0
  numpy_seed: 12345
  optimizer: adam
  print_step_percent: 5.0
  resolution: 0.01
  sim_time: 4.0
  substrate: hx
  torch_seed: 2000
  training_noise: false
  use_forward_integrator: false
  weight_bumping_exp: true
  weight_bumping_targeted: true
  weight_bumping_value: 0.0005
